version: '3.9'

services:
  web:
    build:
      context: .
    container_name: hangcounts-web
    env_file:
      - ./.compose.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hangcounts_local

  db:
    image: postgres:17.2
    container_name: hangcounts_dev_db
    restart: unless-stopped
    shm_size: 128mb
    environment:
        POSTGRES_USER: ${HANGCOUNTS_POSTGRES_USER}
        POSTGRES_PASSWORD: ${HANGCOUNTS_POSTGRES_PASSWORD}
        POSTGRES_DB: ${HANGCOUNTS_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - hangcounts_dev_db:/var/lib/postgresql/data
    networks:
      - hangcounts_local
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 2s
      timeout: 3s
      retries: 3

volumes:
  hangcounts_dev_db:

networks:
  hangcounts_local:
    driver: bridge