version: '3.9'

services:
  web:
    build:
      context: .
    container_name: hangcounts_web
    env_file:
      - ./.compose.env
    depends_on:
      migratedb:
        condition: service_completed_successfully
    networks:
      - hangcounts_local

  # postgres has a feature to do this on its own but this supports more dbs
  # and is what I'll use with kubernetes
  migratedb:
    image: migrate/migrate:v4.18.2
    container_name: hangcounts_migrate_db
    env_file:
      - ./.compose.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hangcounts_local
    volumes:
      - ./migrations/:/migrations
    command: >
      -path /migrations/ 
      -database "postgres://${HANGCOUNTS_POSTGRES_USER}:${HANGCOUNTS_POSTGRES_PASSWORD}@hangcounts_dev_db/${HANGCOUNTS_POSTGRES_DB}?sslmode=disable" 
      up
  db:
    image: postgres:17.2
    container_name: hangcounts_dev_db
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - ./.compose.env
    environment:
        POSTGRES_USER: ${HANGCOUNTS_POSTGRES_USER}
        POSTGRES_PASSWORD: ${HANGCOUNTS_POSTGRES_PASSWORD}
        POSTGRES_DB: ${HANGCOUNTS_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - hangcounts_dev_db:/var/lib/postgresql/data
    networks:
      - hangcounts_local
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "pg_isready -U ${HANGCOUNTS_POSTGRES_USER} -d ${HANGCOUNTS_POSTGRES_DB}"
        ]
      interval: 2s
      timeout: 3s
      retries: 3

volumes:
  hangcounts_dev_db:

networks:
  hangcounts_local:
    driver: bridge